//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resilience.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DiaryEntriesContainer : DbContext
    {
        public DiaryEntriesContainer()
            : base("name=DiaryEntriesContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<DiaryEntries> DiaryEntries { get; set; }
        public virtual DbSet<ExerciseAssign> ExerciseAssigns { get; set; }
        public virtual DbSet<Exercise> Exercises { get; set; }
    }
}
