//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resilience.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DiaryEntries
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Your diary entry cannot be empty")]
        [DataType(DataType.MultilineText)]
        [Display(Name = "Diary Entry")]
        public string Entry { get; set; }
        public int UsersId { get; set; }
        public int MentorId { get; set; }
        public Nullable<double> SentimentScore { get; set; }
        [DataType(DataType.MultilineText)]
        [Display(Name = "Mentor Feedback")]
        public string MentorFeedback { get; set; }
        [Display(Name = "Entry Date")]
        public System.DateTime Date { get; set; }
        [Display(Name = "Mentee Feedback")]
        public Nullable<int> MenteeFeedback { get; set; }
    
        public virtual Users User { get; set; }
    }
}
