//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resilience.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExerciseAssign
    {
        public int Id { get; set; }
        public int MentorId { get; set; }
        public System.DateTime DueDate { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public Nullable<int> MenteeRating { get; set; }
        public string MentorFeedback { get; set; }
        public string MenteeComments { get; set; }
        public int TaskId { get; set; }
        public int UsersId { get; set; }
    
        public virtual Exercise Task { get; set; }
        public virtual Users User { get; set; }
    }
}
