//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resilience.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Exercise
    {
        public int Id { get; set; }
        public string TaskName { get; set; }
        public string TaskDescription { get; set; }
        public Nullable<int> MentorId { get; set; }
        public System.DateTime DueDate { get; set; }
        public System.DateTime CompletionDate { get; set; }
        [DataType(DataType.MultilineText)]
        public string MentorFeedback { get; set; }
        [DataType(DataType.MultilineText)]
        public string MenteeComments { get; set; }
        public string MenteeRating { get; set; }
        public int GoalsId { get; set; }
    
        public virtual Goals Goal { get; set; }
    }
}
