//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resilience.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FamilyViolence
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FamilyViolence()
        {
            this.Regions = new HashSet<Region>();
        }
    
        public int Violence_Id { get; set; }
        public string Year { get; set; }
        public string Numerator { get; set; }
        public string Denominator { get; set; }
        public string Indicator { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Region> Regions { get; set; }
    }
}
