//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resilience.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PlotDataContainer : DbContext
    {
        public PlotDataContainer()
            : base("name=PlotDataContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<Bullying> Bullyings { get; set; }
        public virtual DbSet<Behaviour> Behaviours { get; set; }
        public virtual DbSet<FamilyViolence> FamilyViolences { get; set; }
        public virtual DbSet<FamilyStress> FamilyStresses { get; set; }
    }
}
